name: Test GitHub Action
on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  build:
    name: test the action
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.2
        with:
          ref: ${{ github.head_ref }}

      - name: Create commits
        run: |
          set -o xtrace
          git config user.name 'leemeador'
          git config user.email 'lee@leemeador.com'
          test -d ./testfiles || mkdir ./testfiles
          date +%s > testfiles/report.txt
          git add testfiles/report.txt
          git commit -m "Modify tracked file during workflow"

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v4
        with:
          draft: true
 
      - name: Check outputs
        if: ${{ steps.create-pr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.create-pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.create-pr.outputs.pull-request-url }}"      

      - name: Mark as Ready to release
        uses: ./
        with:
          token: ${{ secrets.GIT_TOKEN }}
          pr-number: ${{ steps.create-pr.outputs.pull-request-number }}

      - name: verify the action
        env:
           GH_TOKEN: ${{ secrets.GIT_TOKEN }}
        shell: bash
        run: |
          set -o xtrace
          export IS_DRAFT="$(gh pr view ${{ steps.create-pr.outputs.pull-request-number }} --json isDraft  --jq .isDraft)"
          echo "isDraft: ${IS_DRAFT}"
          if [ "${IS_DRAFT}" = "true" ]; then
              exit 1
          fi
